import { MongoClient } from "mongodb";
import { GetServerSideProps, InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import Layout from "../src/project/layout/layout";
import ShopTemplate from "../src/project/templates/shopTemplate";

const Shop: NextPage = ({products}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    return (
        <div>
          <Head>
            <title>Cool Air</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <Layout>
                <ShopTemplate {...products}/>
            </Layout>
        </div>
      )
}
 
export default Shop;

export const getServerSideProps: GetServerSideProps = async (context) => {


    const URI: string = process.env.DB_URL!;
  
    const client = await MongoClient.connect(URI);
  
    const db = client.db();
  
    const collection = db.collection("products");
    const documents = await collection.find().toArray();
    return {
      props: {
        products: JSON.parse(JSON.stringify(documents))
      },
    };
  };