import { MongoClient } from "mongodb";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../src/project/layout/layout";
import ShopTemplate from "../src/project/templates/shopTemplate";

const Shop: NextPage = (props: any) => {

  const productsData = props.products;
  const productsCount = props.countDocs

  return (
    <div>
      <Head>
        <title>Cool Air</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ShopTemplate products={productsData} productsCount={productsCount}/>
      </Layout>
    </div>
  );
};

export default Shop;

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  res.setHeader("Cache-Control", "public, s-maxage=10, stale-while-revalidate=59");
  const URI: string = process.env.DB_URL!;

  const client = await MongoClient.connect(URI);

  const db = client.db();

  const collection = db.collection("products");
  const documents = await collection.find().limit(12).toArray();
  const value = await collection.countDocuments()

  return {
    props: {
      products: documents.map((item) => ({
        title: item.title,
        description: item.description,
        price: item.price,
        id: item._id.toString(),
        imageUrl: item.imageUrl
      })),
      countDocs: value
    },
  };
};
